### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by danrabbit**
Contributors to `main` need to sign off in a comment below to licensing as GPLv3:

- [x] @alatiera
- [x] @bilelmoussaoui
- [x] @btkostner 
- [x] @cassidyjames
- [x] @danrabbit
- [x] @Marukesu
- [x] @tintou

### CODE REVIEW

**Comment by cassidyjames** [comment]
:+1: I agree to licensing this repo as GPLv3

**Comment by btkostner** [comment]
:+1:

**Comment by Marukesu** [comment]
I agree with licensing as GPLv3.

**Comment by bilelmoussaoui** [comment]
Ack

**Comment by tintou** [comment]
`Signed-off-by: Corentin Noël <corentin@elementary.io>`

**Comment by alatiera** [comment]
I agree 👍

**Review by cassidyjames — APPROVED** [review]
All parties signed off in comments.

**Pull request merged**
