### PR TITLE
CI: build using github actions

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The CI result can be found at https://github.com/bilelmoussaoui/flatpak-platform/runs/1303037942

**Comment by Marukesu** [comment]
looks like the CI ended in a false positive

**Comment by Marukesu** [comment]
CI Failed abruptly on "Initializing build dir" phase of flatpak-builder.

**Comment by bilelmoussaoui** [comment]
This will be superseded by #22

**Pull request closed without merging**
