### PR TITLE
Release 6.0.0

### PR DESCRIPTION
**Pull request by danrabbit**
- [x] Needs #48
- [x] Needs #49 
- [x] Needs #50

### CODE REVIEW

**Review by btkostner — CHANGES_REQUESTED** [review]
Changing this branch to `6.0.0` means every day we would be publishing a new 6 version. We should probably keep this as `daily` so our cron _just_ builds the daily branch, and we only release a new 6 version when we create a release

**Comment by danrabbit** [comment]
I think that still makes sense to keep the version number up to date. So if we make a change we'd bump the version number in daily

Otherwise we would publish a runtime to the `6` branch with a version of `daily`, right?

**Comment by btkostner** [comment]
Daily GitHub action doesn't have a hard set branch, so it will use the version in the json file. So by changing this, you're making a new branch of `6.0.0`, and the `daily` platform branch will no longer be updated.

If you want, we can change the Daily GitHub action to set the branch to `daily`, then we can change this version to `6` and it would work.

As far as I know, there is no difference between `version` and `branch`. The version is just the branch used.

**Comment by danrabbit** [comment]
Ah yeah okay that's kind of confusing but yeah we should make sure the daily publish action is pushing to `daily` and the release is pushing to major version branches. 

When you run `Flatpak list --runtime` I can confirm that the Gnome runtimes don't seem to be versioned and use branches only. But it does that parts of the freedesktop runtime use both version and branch separately. I think that makes more sense to keep track of minor and patch revisions

For example the version of FreeDesktop platform I have is "20.08.14" and the branch is "20.08"

**Review by btkostner — APPROVED** [review]
This hard sets daily to always be the `daily` branch :heavy_check_mark: 
Will publish releases to the `6` branch :heavy_check_mark: 
Not 100% sure that the `branch: 6.0.0` will have any effect

**Comment by danrabbit** [comment]
Prior to merging, let's poke @Marukesu to see if they have clarifying thoughts on the version stuff :)

**Comment by Marukesu** [comment]
> This hard sets daily to always be the `daily` branch 
> Will publish releases to the `6` branch 
> Not 100% sure that the `branch: 6.0.0` will have any effect

`branch` can't be overriden by the `--default-branch` option on command line, we should use `default-branch` on the manifest too.

About the version column in `flatpak list`, it use the name and version from the appdata file, the same for the name, since we don't include them, the version remains empty and the name fallback for hardcoded ones.

**Comment by btkostner** [comment]
I updated the manifest to `default-branch` and used `daily` so if someone clones the repo and builds it manually, it overwrites the local `daily` branch.

**Comment by danrabbit** [comment]
Okay so it sounds like we need to add AppData here as well. I can take care of that today

**Review by btkostner — APPROVED** [review]
I think this looks good to me

**Pull request merged**
