### PR TITLE
Release 7.2.0

### PR DESCRIPTION
**Pull request by danirabbit**
Includes latest Granite and Stylesheet needed for Web etc

### CODE REVIEW

**Review by zeebok — APPROVED** [review]

**Comment by danirabbit** [comment]
Gotta wait to merge this until we resolve the storage issues so that it will actually build :sweat_smile:

**Review by davidmhewitt — CHANGES_REQUESTED** [review]
As well as waiting for the remote to be fixed, the actions workflows need updating before merging this.

See: https://github.com/elementary/flatpak-platform/pull/104

**Comment by danirabbit** [comment]
Proposed in #118

**Review by davidmhewitt — APPROVED** [review]
Happy for this to be merged if and when this succeeds: https://github.com/elementary/flatpak-platform/actions/runs/4568815344

**Comment by davidmhewitt** [comment]
Seems the actions are partially failing due to the GitHub runners running out of space now 🙄 

I've opened https://github.com/easimon/maximize-build-space/pull/19 , so if that gets merged, we'll be able to get a bit more space on the runners.

But for now, it might be tempting to remove the caching from the workflow as I don't think it gives us much speedup anyway, and it's the compressing and uploading the cache that we're running out of space on.

**Pull request merged**
