### PR TITLE
add io.elementary.Sdk.Docs extension

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by Marukesu** [comment]
`/share/runtime/docs` are in the platform-cleanup, is that right? Don't it make we depend on `org.gnome.Docs` for inherited modules?

Also, the only module that has documentation enabled is handy. I think it make sense to enable it for the others modules in this PR too.

**Comment by alatiera** [comment]
> `/share/runtime/docs` are in the platform-cleanup, is that right?

Yes, it seems to be working, no idea why.

> Don't it make we depend on `org.gnome.Docs` for inherited modules?

Not sure actually, we didn't seem to inherit fd.o.sdk.docs but when we used `flatpak-builder` in gnome.

I am mostly cargo culting from how we were building the gnome runtime like 3 years ago.

**Comment by alatiera** [comment]
No idea what these are about

```
DateTime.vala:76.39-76.53: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Granite.DateTime.get_relative_datetime'
DateTime.vala:79.39-79.53: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Granite.DateTime.get_relative_datetime'
DateTime.vala:85.39-85.53: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Granite.DateTime.get_relative_datetime'
DateTime.vala:88.39-88.53: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Granite.DateTime.get_relative_datetime'
```

**Comment by jeremypw** [comment]
CLosing as not reviewed/actioned after 2+yrs

**Pull request closed without merging**
