### PR TITLE
Release Action: Allow manual dispatch

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Review by btkostner — CHANGES_REQUESTED** [review]
Because of the `if` in the `publish_platform` job, you will be able to manually dispatch this, but it will skip the actual publishing because it didn't come from a PR with a `Release` label.

**Comment by danrabbit** [comment]
Is there a way to work around that?

**Comment by btkostner** [comment]
1) Just make another release because that's probably the easiest

2) Update the `if` statement to take into account manual runs. `workflow_dispatch` adds `github.event.inputs` but because we are not sending any input, I'm not sure if there is an accurate way to tell if it's just ran with `workflow_dispatch`. If you can find a way, then we can just rewrite the `if` to something like `workflow_was_dispatched or (github.event.pull_request.merged == true && true == contains(join(github.event.pull_request.labels.*.name), 'Release'))`

    Docs: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

**Comment by danrabbit** [comment]
The problem we're facing right now is that there's been no changes to the platform but we want to kick off builds for arm. If we made another (empty) release, that's a several hundred MB update for all of our users that contains 0 changes

I guess another kind of shitty hack way is we could make a copy of the workflow called "manual-release" and then delete it after

**Comment by btkostner** [comment]
Because all of the dependencies are locked on the platform manifest, it will work similar to how the `daily` branch for the platform works. Which flatpak would only download the diff of. From my latest `flatpak update`:

```
 3. [✓] io.elementary.Platform                  daily            u            appcenter             1.0 kB / 356.6 MB
```

Only results in 1kB

**Comment by davidmhewitt** [comment]
Indeed, Flatpak does diff based updates, so there's no harm in pushing a new update. Flatpak had no concept of what "release" we've tagged.

In fact, the GNOME platform we're based on isn't immutable. It's perfectly feasible that it would have changed as a result of security updates or bug fixes. Which raises the question of how are we tracking that and pushing updates when needed?

**Comment by danrabbit** [comment]
Alright, good points! nvm then. Closing :)

**Pull request closed without merging**
