### PR TITLE
Use Granite master

### PR DESCRIPTION
**Pull request by cassidyjames**
I think this is all that needs to be done? Blocked until https://github.com/elementary/granite/pull/487 is merged. :smile:

### CODE REVIEW

**Comment by alatiera** [comment]
Given that the runtime now has a daily tag, we might as well point everything to main directly and tag for stable runtimes.

**Comment by cassidyjames** [comment]
@alatiera that makes a lot more sense to me

**Comment by alatiera** [comment]
Looks good :+1:

**Comment by danrabbit** [comment]
I'm not sure we should be making the runtime more unstable since we're trying to work towards beta and want developers to starting being able to build for 6.0.

This is especially hasty since we have #28 and #29 and it sounds like this granite function may not be necessary after all

**Comment by Marukesu** [comment]
If I recall correctly, settings.ini doesn't work for flatpak ever if part of runtime, GTK will use the settings portal instead, also, #29 works only when the theme is elementary, if the user use adwaita it will get adwaita.

**Pull request closed without merging**
